services:
  - type: web
    name: edutrack
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app --workers 1 --bind 0.0.0.0:$PORT --log-file -
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: sqlite:////opt/render/project/src/edutrack.db
      - key: PYTHON_VERSION
        value: 3.11.9
